### PR TITLE
Updating simulateEvent in the plugin, as well as in the sample app in this repo.

### PR DESCRIPTION
**Pull request by LeonidJack**
Apparently, originally, I tried using the separate repo as my sample app. This time I tried using the zipped sample project in the plugin repo, and it worked almost right away. All I have to do was generate the android build and run.

3 things:

1. I think we should take down the NeuraSampleCordova repo and replace it with the one in the zip inside the cordova-neura-plugin, which worked seamlessly.

Looking at the app that works:
2. There was a crash the first time I tried to authenticate but it hasn't happened again. Might not need to worry about that. (Update:) The app is actually crashing in the background multiple times while I use my phone.
3. The simulateEvent action in the sample app uses the deprecated simulateEvent and does not work. We need to update this in the neura plugin (and also the sample app).

Also, the sample app in the zip already has the plugins installed, so I didn't need to worry about messing with them.

Also, I'm pretty sure the code in NeuraSampleCordova simply doesn't work. The fixes I made to it before I tried the other sample app (which works) nearly match the code in the plugin sample app. That is another reason why I think we should look at changing/removing the NeuraSampleCordova repo.

### CODE REVIEW

**Comment by brandecho** [comment]
Is this the url to the zip file that you stated "works"? https://github.com/NeuraLabs/cordova-neura-plugin/blob/master/NeuraSampleCordova.zip

**Comment by LeonidJack** [comment]
Yes, and this is the one that "doesn't work" (only as I've tried to use it): https://github.com/NeuraLabs/NeuraSampleCordova

**Comment by youvalv** [comment]
@brandecho thank you for asking for clarification. 
I asked @LeonidJack review the plug-in and app to see if there are any gaps.

**Comment by youvalv** [comment]
@LeonidJack I now realised you used the master branch instead of the "update-to-sdk-4" branch on https://github.com/NeuraLabs/NeuraSampleCordova. 
it's now merged to master

**Pull request merged**
